### ISSUE TITLE
Step 2 of setting up MSYS2

### ISSUE THREAD

**Issue by osmium8** [FOSSEE/FOSSEE-Optimization-toolbox#47]
https://github.com/FOSSEE/FOSSEE-Optimization-toolbox/blob/Scilab-6/doc/INSTALL.mingw

STEP 2.5

```pacman -S pkgconfig
error: target not found: pkgconfig

we can use pkg-config or pkgconf ( conflicting packages )

**Comment by ashutoshmahajan** [comment]
Changed to pkg-config. Pranshu, please close the issue if the fix looks OK.
