### ISSUE TITLE
Copy all integer programming functions from FOSSEE-Optim-toolbox-development

### ISSUE THREAD

**Issue by ashutoshmahajan** [FOSSEE/FOSSEE-Optimization-toolbox#6]
FOSSEE-Optim-toolbox-development will be deleted. All functions in that repository must be copied here

1. cbcintlinprog
2. intfminbnd
3. intfminunc
4. intfmincon
5. intfminimax
6. intqpipopt

**Comment by JRGJON** [comment]
Copied and integrated all the functions.
